export const ADD_CATEGORY="ADD_CATEGORY"
export const DELETE_CATEGORY="DELETE_CATEGORY"
export const EDIT_CATEGORY="EDIT_CATEGORY"
export const GET_CATEGORY="GET_CATEGORY"

export const ADD_SUBCATEGORY="ADD_SUBCATEGORY"
export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY"
export const EDIT_SUBCATEGORY="EDIT_SUBCATEGORY"
export const GET_SUBCATEGORY="GET_SUBCATEGORY"